 # Ciencia de datos en Python
## Heberto Jose Alegre Ordoñez
    
  **Diferencia entre np. matrix y np.ndarray** 
    

## nump. matrix

Devuelve una matriz de un objeto similar a una matriz o de una cadena de datos. Una matriz es una matriz 2-D especializada que conserva su naturaleza 2-D a través de las operaciones. Tiene ciertos operadores especiales, como * (multiplicación de matrices) y ** (potencia de matriz).

fuente: https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html

## numpy. ndarray


Un objeto de matriz representa una matriz homogénea y multidimensional de elementos de tamaño fijo. Un objeto de tipo de datos asociado describe el formato de cada elemento de la matriz (su orden de bytes, la cantidad de bytes que ocupa en la memoria, si es un número entero, un número de punto flotante o algo más, etc.)

fuente: https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.html

In [1]:
import numpy as np

In [2]:
# Para este ejemplo se utilizo la siguente linea de código 

a = np.matrix('4 3 8; 7 5 6')
print(a)

[[4 3 8]
 [7 5 6]]


Se observa que la instrucción para *np.matrix* resulta en escribir por linea la matriz que se necesita, separando las filas por ";"

In [6]:
 np.ndarray(shape=(3,3), dtype=int, order='F')

array([[-116977168,    7012457,    6881378],
       [        85,    6619252,    6029422],
       [   7143516,    6029432,    3539064]])

Como se observa la función np. ndarray puede servir para generar una matrix de dimensión nxm (sin restricciones) que que introduzca valores aleatorios ya sea de entero  o con decimales.